#!/usr/bin/env node
// Compute the audit disagreement rate and write docs/findings.md.
//
// The sample deliberately oversamples rare tiers, so the RAW sample rate is not the
// population rate. Both are reported, along with per-stratum rates, and the weighted
// figure is the one that means anything. Publishing a tuned number would defeat the
// purpose of running the audit at all.

import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url).pathname;
const db = new DatabaseSync(`${root}db/gapmap.sqlite`);
const all = (s, ...p) => db.prepare(s).all(...p);
const one = (s, ...p) => db.prepare(s).get(...p);

const manifest = JSON.parse(readFileSync(`${root}research-log/audit-tasks/manifest.json`, 'utf8'));
const stratumOf = Object.fromEntries(manifest.map((m) => [m.gap_id, m.stratum]));

const L = [];
const w = (s = '') => L.push(s);

w('# Findings');
w();
w('Generated by `engine/audit-report.mjs`. Covers all 103 gaps in Convergent Research\'s 2026-07-29 export.');
w();

w('## Measurability tier distribution');
w();
w('| Tier | Gaps | Share |');
w('|---|---:|---:|');
const tiers = all('SELECT tier, count(*) c FROM gap_measurability GROUP BY tier ORDER BY c DESC');
const total = tiers.reduce((a, r) => a + r.c, 0);
for (const r of tiers) w(`| ${r.tier} | ${r.c} | ${(100 * r.c / total).toFixed(0)}% |`);
w();

w('## Primary AI capability type');
w();
w('| Type | Gaps | Share |');
w('|---|---:|---:|');
for (const r of all('SELECT ai_type, count(*) c FROM gap_ai_types WHERE is_primary=1 GROUP BY ai_type ORDER BY c DESC'))
  w(`| ${r.ai_type} | ${r.c} | ${(100 * r.c / total).toFixed(0)}% |`);
w();

w('## Maturity of the primary type');
w();
w('| Maturity | Gaps | Share |');
w('|---|---:|---:|');
for (const r of all("SELECT maturity, count(*) c FROM gap_ai_types WHERE is_primary=1 GROUP BY maturity ORDER BY CASE maturity WHEN 'Working now' THEN 1 WHEN '2-5 years' THEN 2 ELSE 3 END"))
  w(`| ${r.maturity} | ${r.c} | ${(100 * r.c / total).toFixed(0)}% |`);
w();

w('## Cross-tab: measurability tier against primary AI type');
w();
const types = all('SELECT DISTINCT ai_type FROM gap_ai_types WHERE is_primary=1 ORDER BY ai_type').map((r) => r.ai_type);
const tierNames = ['Directly measurable', 'Proxy only', 'Verification contested', 'Counterfactual required'];
w(`| Primary AI type | ${tierNames.map((t) => t.replace('Directly measurable', 'Direct').replace('Verification contested', 'Contested').replace('Counterfactual required', 'Counterfactual').replace('Proxy only', 'Proxy')).join(' | ')} | Total |`);
w(`|---|${tierNames.map(() => '---:').join('|')}|---:|`);
for (const t of types) {
  const cells = tierNames.map((tier) =>
    one(`SELECT count(*) c FROM gap_ai_types a JOIN gap_measurability m ON m.gap_id=a.gap_id
         WHERE a.is_primary=1 AND a.ai_type=? AND m.tier=?`, t, tier).c);
  w(`| ${t} | ${cells.join(' | ')} | ${cells.reduce((a, b) => a + b, 0)} |`);
}
w();

w('## Cross-tab: measurability tier against field');
w();
w('| Field | Direct | Proxy | Contested | Counterfactual |');
w('|---|---:|---:|---:|---:|');
for (const f of all('SELECT DISTINCT f.name FROM gm_fields f JOIN gm_gaps g ON g.field_id=f.id ORDER BY f.name')) {
  const cells = tierNames.map((tier) =>
    one(`SELECT count(*) c FROM gm_gaps g JOIN gm_fields f ON f.id=g.field_id
         JOIN gap_measurability m ON m.gap_id=g.id WHERE f.name=? AND m.tier=?`, f.name, tier).c);
  w(`| ${f.name} | ${cells.join(' | ')} |`);
}
w();

w('## Audit');
w();
const sampled = manifest.length;
w(`A second labeler, which never saw the original labels, independently relabeled a stratified sample of **${sampled} of 103 gaps** (${(100 * sampled / 103).toFixed(0)}%). The sample deliberately oversamples the rare tiers, because that is where the taxonomy is hardest and a disagreement rate is most informative. That biases the raw sample rate upward, so the population-weighted figure below is the one that means anything.`);
w();
w('Outcome sentences are free text. Exact match is meaningless on free text and a string heuristic would be worse than useless, so outcome rows are stored for qualitative comparison and excluded from these rates.');
w();

for (const dim of ['measurability', 'ai_type']) {
  const rows = all('SELECT gap_id, original, audit, agreed FROM audits WHERE dimension = ?', dim);
  if (!rows.length) continue;
  const label = dim === 'measurability' ? 'Measurability tier' : 'Primary AI capability type';
  const agr = rows.filter((r) => r.agreed).length;
  w(`### ${label}`);
  w();
  w(`Raw sample agreement: **${agr}/${rows.length}** (${(100 * agr / rows.length).toFixed(0)}%), disagreement ${(100 * (rows.length - agr) / rows.length).toFixed(0)}%.`);
  w();

  if (dim === 'measurability') {
    w('Per stratum:');
    w();
    w('| Stratum (original tier) | Population | Sampled | Agree | Disagreement |');
    w('|---|---:|---:|---:|---:|');
    let weighted = 0, popTotal = 0;
    for (const tier of tierNames) {
      const inStratum = rows.filter((r) => stratumOf[r.gap_id] === tier);
      if (!inStratum.length) continue;
      const pop = one('SELECT count(*) c FROM gap_measurability WHERE tier = ?', tier).c;
      const a = inStratum.filter((r) => r.agreed).length;
      const dis = (inStratum.length - a) / inStratum.length;
      weighted += dis * pop; popTotal += pop;
      w(`| ${tier} | ${pop} | ${inStratum.length} | ${a} | ${(100 * dis).toFixed(0)}% |`);
    }
    w();
    w(`**Population-weighted disagreement: ${(100 * weighted / popTotal).toFixed(0)}%.**`);
    w();
  }

  const dis = rows.filter((r) => !r.agreed);
  if (dis.length) {
    w('Disagreements:');
    w();
    w('| Gap | Original | Audit |');
    w('|---|---|---|');
    for (const r of dis) {
      const g = one('SELECT name FROM gm_gaps WHERE id = ?', r.gap_id).name.replace(/\s+/g, ' ');
      w(`| ${g} | ${r.original} | ${r.audit} |`);
    }
    w();
  }
}

// The two sections below are Phase 6 additions: the contrasting pair the brief asks
// for, and the elapsed-time figure split into agent and human review. A single
// blended time number invites the obvious objection, so it is never computed.
w('## The clearest contrasting pair');
w();
{
  const pick = (tier, mat, type) => one(`
    SELECT g.name, f.name AS field, m.tier, a.ai_type, a.maturity, o.outcome
    FROM gm_gaps g JOIN gm_fields f ON f.id=g.field_id
    JOIN gap_measurability m ON m.gap_id=g.id
    JOIN gap_ai_types a ON a.gap_id=g.id AND a.is_primary=1
    JOIN gap_outcomes o ON o.gap_id=g.id
    WHERE m.tier=? AND a.maturity=? AND a.ai_type=? LIMIT 1`, tier, mat, type);
  const easy = pick('Directly measurable', 'Working now', 'Design and optimization search')
            ?? pick('Directly measurable', 'Working now', 'LLM reasoning and synthesis');
  const hard = pick('Counterfactual required', 'Speculative', 'Coordination and institutional')
            ?? pick('Verification contested', 'Speculative', 'Coordination and institutional');
  if (easy && hard) {
    w(`Two gaps sitting in the same catalogue, one row apart in structure and a category apart in what can be known about them.`);
    w();
    w('| | Most tractable end | Least tractable end |');
    w('|---|---|---|');
    w(`| Gap | ${easy.name.replace(/\s+/g, ' ')} | ${hard.name.replace(/\s+/g, ' ')} |`);
    w(`| Field | ${easy.field} | ${hard.field} |`);
    w(`| Measurability | ${easy.tier} | ${hard.tier} |`);
    w(`| Primary AI type | ${easy.ai_type} | ${hard.ai_type} |`);
    w(`| Maturity | ${easy.maturity} | ${hard.maturity} |`);
    w();
    w(`A catalogue treats these as two rows of equal standing, which for a catalogue is correct — it is not claiming otherwise. The four added columns are what make the difference visible: one has a quantity, a direction and a tool that works today; the other has none of the three, and the honest thing to record is that its progress indicator search returned a null.`);
    w();
  }
}

{
  const ind = all(`SELECT i.*, g.name AS gap, m.tier FROM gap_indicators i
                   JOIN gm_gaps g ON g.id=i.gap_id
                   LEFT JOIN gap_measurability m ON m.gap_id=i.gap_id ORDER BY i.id`);
  const nulls = ind.filter((i) => i.is_null_result);
  // Count the nulls, do not assert them. This heading was the literal string "and the
  // two nulls" while the table it introduces was generated from the database, so when
  // Gate A replaced the false quantum-gravity null the heading went on claiming a
  // second one. A generated document with a hand-written headline is a document that
  // can contradict itself thirteen lines apart, and this one did.
  const word = ['no nulls', 'the null', 'the two nulls', 'the three nulls'][nulls.length] ?? `the ${nulls.length} nulls`;
  w(`## Progress indicators, and ${word}`);
  w();
  w(`A **sample** of ${ind.length} gaps across all four tiers, ${nulls.length} of them ${nulls.length === 1 ? 'an honest null' : 'honest nulls'}. Not coverage, and not to be extrapolated to the other ${103 - ind.length}. Every non-null value was read off a page that was actually fetched; the \`source_checked\` column records whether the source verified against arXiv or Crossref, or was merely reachable.`);
  w();
  w('| Gap | Tier | Quantity | Current | Source check |');
  w('|---|---|---|---|---|');
  for (const i of ind)
    w(`| ${i.gap.replace(/\s+/g, ' ')} | ${i.tier} | ${i.quantity} | ${i.is_null_result ? '**null**' : `${i.current_value} ${i.unit ?? ''}`} | ${i.source_checked ?? 'n/a'} |`);
  w();
  w(`The nulls are the load-bearing rows. Each has six logged, cached searches behind it and each names its closest near-miss: a real and improving Fermi/LHAASO bound on the quantum-gravity energy scale that no one agrees settles anything, and the ~42% administrative-burden figure that measures a symptom of institutional rigidity rather than the research it prevents. See \`search_log\` and \`research-log/searches/phase-3.json\`.`);
  w();
}

w('## Critical paths');
w();
{
  for (const p of all('SELECT * FROM critical_paths ORDER BY id')) {
    const links = all('SELECT * FROM critical_path_links WHERE path_id=? ORDER BY seq', p.id);
    const bind = links.filter((l) => l.is_binding);
    w(`- **${p.title}** — axis: ${p.axis}. ${bind.length} of ${links.length} links bind: ${bind.map((l) => l.link).join(', ')}.`);
  }
  w();
  w('Both expectations were committed before the link analysis existed, in a separate commit, so the ordering is checkable in git. Full chains, evidence and the cross-field intersection: `docs/critical-paths.md`.');
  w();
}

w('## Elapsed time');
w();
{
  // Sum in milliseconds and round once. Rounding each phase and then summing gives a
  // different total from the artifact's, and two published figures that disagree by a
  // minute is exactly the kind of thing that costs more trust than the minute is worth.
  // Some runs rows already carry a trailing Z, some do not. Appending one
  // unconditionally produced '...ZZ', which Date parses as NaN and which printed
  // fifteen NaN cells plus 'Agent time: NaN minutes' into docs/findings.md.
  const iso = (t) => { const x = t.replace(' ', 'T'); return x.endsWith('Z') ? x : x + 'Z'; };
  const ms = (r) => new Date(iso(r.ended_at)) - new Date(iso(r.started_at));
  const runs = all('SELECT phase, kind, started_at, ended_at, n_units, note FROM runs ORDER BY id');
  w('| Phase | Kind | Units | Elapsed |');
  w('|---|---|---:|---:|');
  let agentMs = 0, humanMs = 0;
  for (const r of runs) {
    const d = r.ended_at ? ms(r) : null;
    if (d !== null) (r.kind === 'agent' ? (agentMs += d) : (humanMs += d));
    w(`| ${r.phase} | ${r.kind} | ${r.n_units ?? '—'} | ${d === null ? 'open' : Math.round(d / 60000) + ' min'} |`);
  }
  const agent = Math.round(agentMs / 60000), human = Math.round(humanMs / 60000);
  w();
  w(`**Agent time: ${agent} minutes. Human review time: ${human} minutes.** Tracked separately on purpose; a single blended number invites the obvious objection. Phase 0's start was never instrumented, so it counts as zero and the agent figure is a lower bound.`);
  w();
}

w('## What this shows');
w();
const wn = {}, tot = {};
for (const r of all("SELECT ai_type, maturity, count(*) c FROM gap_ai_types WHERE is_primary=1 GROUP BY ai_type, maturity")) {
  tot[r.ai_type] = (tot[r.ai_type] || 0) + r.c;
  if (r.maturity === 'Working now') wn[r.ai_type] = r.c;
}
const gradient = Object.keys(tot)
  .map((t) => ({ type: t, wn: wn[t] || 0, tot: tot[t], pct: 100 * (wn[t] || 0) / tot[t] }))
  .sort((a, b) => b.pct - a.pct);

w('### The maturity gradient did not replicate');
w();
w('An earlier version of this document reported a monotone gradient — the share of each');
w('capability type already working now running smoothly from LLM reasoning at the top to');
w('physical build at zero — and read it as the verifier\'s-law prediction confirmed on');
w('someone else\'s data. **A full independent relabel of all 103 gaps did not reproduce it.**');
w();
w('| Primary AI type | v1 working-now | v2 working-now |');
w('|---|---:|---:|');
w('| Coordination and institutional | 7% | 67% |');
w('| LLM reasoning and synthesis | 60% | 60% |');
w('| Autonomous experimentation | 40% | 56% |');
w('| Sensing and signal processing | 20% | 53% |');
w('| Real-time control of physical systems | n/a | 50% |');
w('| ML surrogates and prediction | 30% | 14% |');
w('| Design and optimization search | 19% | 13% |');
w('| Physical build and manipulation | 0% | 13% |');
w();
w('The ordering inverts at the top. Coordination and institutional moves from last to first.');
w('Physical build stops being zero. Maturity agreement between the two passes was 63 of 103,');
w('and 23 of the 40 disagreements moved the same direction, from `2-5 years` to `Working now`.');
w();
w('The cause is a definitional ambiguity the earlier revision did not close: does `Working');
w('now` mean the capability **exists** or that applying it **would move this gap**? For');
w('technical categories the readings coincide. For institutional ones they do not — convening');
w('a standards body is available today; getting universal DNA-synthesis screening adopted is');
w('not. See `methodology/taxonomy.md` ambiguity (b).');
w();
w('**Consequence: the verifiability gradient is withdrawn as a finding.** It was the most');
w('striking thing this analysis produced and it does not survive independent replication.');
w('Maturity is reported per gap with its disagreement rate attached, and no aggregate claim');
w('rests on it.');
w();
w('### What does survive');
w();
const llmTot = one("SELECT count(*) c FROM gap_ai_types WHERE is_primary=1 AND ai_type='LLM reasoning and synthesis'").c;
w(`**The type distribution is the stable result.** Primary AI type agreed on 77 of 103 gaps`);
w('between two independent passes (25% disagreement), against 61% agreement on maturity.');
w('Two figures held almost exactly across both passes:');
w();
w(`- **LLM reasoning and synthesis is primary for ${llmTot} of 103 gaps** — identical in v1 and v2 — and 60% working-now in both. The cognitive layer is a small and well-characterised slice of this map.`);
w('- Coordination and institutional is primary for 15 of 103 in both passes. The two passes disagree sharply about how *mature* institutional capability is, and not at all about how *often* it is the primary constraint.');
w();
w('So the defensible version of the claim is the weaker one: **LLM-shaped work is primary');
w('for about a tenth of the map, and the rest is spread across sensing, prediction, design,');
w('build and institutions.** The stronger claim — that AI maturity tracks verifiability in a');
w('clean ordering — is not supported by this data at this level of measurement reliability.');
w();
w('### A category that does not work');

w();
w('The audit found that **Proxy only cannot be applied reliably.** It ran 78% disagreement against 0% for Directly measurable and 9% for Verification contested, and all three auditors independently reported it was repeatedly the nearest alternative and almost never won. Every Proxy only assignment has therefore been downgraded to `guess`, including the ones the auditor did not sample.');
w();
w('This matters for reading everything above: the tiers that carry the argument are the two that held up. Tier 1 and tier 3 are reliable; the residual category between them is not, and a future version should either define it more sharply or drop it.');
w();
w('### Taxonomy gaps found by audit');
w();
w('Three cases where the seven-type taxonomy has no right answer, all surfaced independently by blind auditors:');
w();
w('- **Closed-loop control of a physical system** has no home. Fusion plasma control chooses no experiments, so it is not autonomous experimentation, and it builds nothing, so it is not physical build. This is a defensible eighth category.');
w('- **Gaps where AI is the object rather than the instrument** (AI misuse, rogue AI, narrow reasoning) have no safety-and-robustness-research bucket.');
w('- **Composite gaps** bundle sub-problems that would take different types *and different tiers*, so a single primary loses real information.');
w();
w('## Confidence flags');
w();
w('| Dimension | Confident | Guess |');
w('|---|---:|---:|');
for (const [d, t, where] of [['Outcome', 'gap_outcomes', ''], ['Primary AI type', 'gap_ai_types', 'WHERE is_primary=1'], ['Measurability tier', 'gap_measurability', '']]) {
  const c = one(`SELECT count(*) c FROM ${t} ${where} ${where ? 'AND' : 'WHERE'} confidence='confident'`).c;
  const g = one(`SELECT count(*) c FROM ${t} ${where} ${where ? 'AND' : 'WHERE'} confidence='guess'`).c;
  w(`| ${d} | ${c} | ${g} |`);
}
w();

writeFileSync(`${root}docs/findings.md`, L.join('\n'));
console.log(`wrote docs/findings.md (${L.length} lines)`);
