#!/usr/bin/env node
// Compute the audit disagreement rate and write docs/findings.md.
//
// The sample deliberately oversamples rare tiers, so the RAW sample rate is not the
// population rate. Both are reported, along with per-stratum rates, and the weighted
// figure is the one that means anything. Publishing a tuned number would defeat the
// purpose of running the audit at all.

import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url).pathname;
const db = new DatabaseSync(`${root}db/gapmap.sqlite`);
const all = (s, ...p) => db.prepare(s).all(...p);
const one = (s, ...p) => db.prepare(s).get(...p);

const manifest = JSON.parse(readFileSync(`${root}research-log/audit-tasks/manifest.json`, 'utf8'));
const stratumOf = Object.fromEntries(manifest.map((m) => [m.gap_id, m.stratum]));

const L = [];
const w = (s = '') => L.push(s);

w('# Findings');
w();
w('Generated by `engine/audit-report.mjs`. Covers all 103 gaps in Convergent Research\'s 2026-07-29 export.');
w();

w('## Measurability tier distribution');
w();
w('| Tier | Gaps | Share |');
w('|---|---:|---:|');
const tiers = all('SELECT tier, count(*) c FROM gap_measurability GROUP BY tier ORDER BY c DESC');
const total = tiers.reduce((a, r) => a + r.c, 0);
for (const r of tiers) w(`| ${r.tier} | ${r.c} | ${(100 * r.c / total).toFixed(0)}% |`);
w();

w('## Primary AI capability type');
w();
w('| Type | Gaps | Share |');
w('|---|---:|---:|');
for (const r of all('SELECT ai_type, count(*) c FROM gap_ai_types WHERE is_primary=1 GROUP BY ai_type ORDER BY c DESC'))
  w(`| ${r.ai_type} | ${r.c} | ${(100 * r.c / total).toFixed(0)}% |`);
w();

w('## Maturity of the primary type');
w();
w('| Maturity | Gaps | Share |');
w('|---|---:|---:|');
for (const r of all("SELECT maturity, count(*) c FROM gap_ai_types WHERE is_primary=1 GROUP BY maturity ORDER BY CASE maturity WHEN 'Working now' THEN 1 WHEN '2-5 years' THEN 2 ELSE 3 END"))
  w(`| ${r.maturity} | ${r.c} | ${(100 * r.c / total).toFixed(0)}% |`);
w();

w('## Cross-tab: measurability tier against primary AI type');
w();
const types = all('SELECT DISTINCT ai_type FROM gap_ai_types WHERE is_primary=1 ORDER BY ai_type').map((r) => r.ai_type);
const tierNames = ['Directly measurable', 'Proxy only', 'Verification contested', 'Counterfactual required'];
w(`| Primary AI type | ${tierNames.map((t) => t.replace('Directly measurable', 'Direct').replace('Verification contested', 'Contested').replace('Counterfactual required', 'Counterfactual').replace('Proxy only', 'Proxy')).join(' | ')} | Total |`);
w(`|---|${tierNames.map(() => '---:').join('|')}|---:|`);
for (const t of types) {
  const cells = tierNames.map((tier) =>
    one(`SELECT count(*) c FROM gap_ai_types a JOIN gap_measurability m ON m.gap_id=a.gap_id
         WHERE a.is_primary=1 AND a.ai_type=? AND m.tier=?`, t, tier).c);
  w(`| ${t} | ${cells.join(' | ')} | ${cells.reduce((a, b) => a + b, 0)} |`);
}
w();

w('## Cross-tab: measurability tier against field');
w();
w('| Field | Direct | Proxy | Contested | Counterfactual |');
w('|---|---:|---:|---:|---:|');
for (const f of all('SELECT DISTINCT f.name FROM gm_fields f JOIN gm_gaps g ON g.field_id=f.id ORDER BY f.name')) {
  const cells = tierNames.map((tier) =>
    one(`SELECT count(*) c FROM gm_gaps g JOIN gm_fields f ON f.id=g.field_id
         JOIN gap_measurability m ON m.gap_id=g.id WHERE f.name=? AND m.tier=?`, f.name, tier).c);
  w(`| ${f.name} | ${cells.join(' | ')} |`);
}
w();

w('## Audit');
w();
const sampled = manifest.length;
w(`A second labeler, which never saw the original labels, independently relabeled a stratified sample of **${sampled} of 103 gaps** (${(100 * sampled / 103).toFixed(0)}%). The sample deliberately oversamples the rare tiers, because that is where the taxonomy is hardest and a disagreement rate is most informative. That biases the raw sample rate upward, so the population-weighted figure below is the one that means anything.`);
w();
w('Outcome sentences are free text. Exact match is meaningless on free text and a string heuristic would be worse than useless, so outcome rows are stored for qualitative comparison and excluded from these rates.');
w();

for (const dim of ['measurability', 'ai_type']) {
  const rows = all('SELECT gap_id, original, audit, agreed FROM audits WHERE dimension = ?', dim);
  if (!rows.length) continue;
  const label = dim === 'measurability' ? 'Measurability tier' : 'Primary AI capability type';
  const agr = rows.filter((r) => r.agreed).length;
  w(`### ${label}`);
  w();
  w(`Raw sample agreement: **${agr}/${rows.length}** (${(100 * agr / rows.length).toFixed(0)}%), disagreement ${(100 * (rows.length - agr) / rows.length).toFixed(0)}%.`);
  w();

  if (dim === 'measurability') {
    w('Per stratum:');
    w();
    w('| Stratum (original tier) | Population | Sampled | Agree | Disagreement |');
    w('|---|---:|---:|---:|---:|');
    let weighted = 0, popTotal = 0;
    for (const tier of tierNames) {
      const inStratum = rows.filter((r) => stratumOf[r.gap_id] === tier);
      if (!inStratum.length) continue;
      const pop = one('SELECT count(*) c FROM gap_measurability WHERE tier = ?', tier).c;
      const a = inStratum.filter((r) => r.agreed).length;
      const dis = (inStratum.length - a) / inStratum.length;
      weighted += dis * pop; popTotal += pop;
      w(`| ${tier} | ${pop} | ${inStratum.length} | ${a} | ${(100 * dis).toFixed(0)}% |`);
    }
    w();
    w(`**Population-weighted disagreement: ${(100 * weighted / popTotal).toFixed(0)}%.**`);
    w();
  }

  const dis = rows.filter((r) => !r.agreed);
  if (dis.length) {
    w('Disagreements:');
    w();
    w('| Gap | Original | Audit |');
    w('|---|---|---|');
    for (const r of dis) {
      const g = one('SELECT name FROM gm_gaps WHERE id = ?', r.gap_id).name.replace(/\s+/g, ' ');
      w(`| ${g} | ${r.original} | ${r.audit} |`);
    }
    w();
  }
}

w('## What this shows');
w();
const wn = {}, tot = {};
for (const r of all("SELECT ai_type, maturity, count(*) c FROM gap_ai_types WHERE is_primary=1 GROUP BY ai_type, maturity")) {
  tot[r.ai_type] = (tot[r.ai_type] || 0) + r.c;
  if (r.maturity === 'Working now') wn[r.ai_type] = r.c;
}
const gradient = Object.keys(tot)
  .map((t) => ({ type: t, wn: wn[t] || 0, tot: tot[t], pct: 100 * (wn[t] || 0) / tot[t] }))
  .sort((a, b) => b.pct - a.pct);

w('### AI maturity tracks verifiability, not importance');
w();
w('Share of each capability type\'s primary assignments that are already **working now**:');
w();
w('| Primary AI type | Working now | Total | Share |');
w('|---|---:|---:|---:|');
for (const g of gradient) w(`| ${g.type} | ${g.wn} | ${g.tot} | ${g.pct.toFixed(0)}% |`);
w();
const top = gradient[0], bottom = gradient[gradient.length - 1];
w(`The gradient runs from **${top.type}** at ${top.pct.toFixed(0)}% down to **${bottom.type}** at ${bottom.pct.toFixed(0)}%. Not one gap in the entire map has physical build and manipulation as a working-now primary: all ${tot['Physical build and manipulation']} of them sit at 2-5 years or speculative. Coordination and institutional manages ${wn['Coordination and institutional'] || 0} of ${tot['Coordination and institutional']}.`);
w();
w('This is the ordering the verifier\'s-law framing predicts. Where feedback is fast and objective, AI has arrived. Where it is slow, contested, or absent, it has not.');
w();

const llmWn = one("SELECT count(*) c FROM gap_ai_types WHERE is_primary=1 AND ai_type='LLM reasoning and synthesis' AND maturity='Working now'").c;
const llmWnProxy = one("SELECT count(*) c FROM gap_ai_types a JOIN gap_measurability m ON m.gap_id=a.gap_id WHERE a.is_primary=1 AND a.ai_type='LLM reasoning and synthesis' AND a.maturity='Working now' AND m.tier!='Directly measurable'").c;
w('### Where the cognitive tools have arrived, the field often cannot tell whether they helped');
w();
w(`LLM reasoning and synthesis is the primary capability for only ${tot['LLM reasoning and synthesis']} of 103 gaps, and ${llmWn} of those are working now — the highest working-now share of any type. But ${llmWnProxy} of those ${llmWn} sit outside tier 1, mostly at proxy-only measurability.`);
w();
w('Metascience is the clearest instance. Its two gaps with a working-now LLM primary, literature synthesis and fraud detection, are both proxy-only: retractions measure detection capability, not fraud prevalence, and synthesis benchmarks do not measure whether knowledge became cumulative. Its one gap with a purely institutional primary is the map\'s only counterfactual-required case.');
w();

const nonCog = one("SELECT count(*) c FROM gap_ai_types WHERE is_primary=1 AND ai_type IN ('Physical build and manipulation','Coordination and institutional','Autonomous experimentation')").c;
w('### The expected finding, tested');
w();
w(`The prediction recorded before labeling was that LLM-shaped work would prove largely saturated and that most remaining gaps would be limited by physical build, fabrication, or institutions. **Confirmed, and by a sharper mechanism than expected.** Physical build, institutional coordination and autonomous experimentation together take ${nonCog} of 103 primaries (${(100 * nonCog / 103).toFixed(0)}%), against ${tot['LLM reasoning and synthesis']} for LLM reasoning. The stronger result is not the count but the maturity gradient above: the constraint is not that few gaps are cognitive, it is that the non-cognitive categories never reach working-now at all.`);
w();
w('### A category that does not work');
w();
w('The audit found that **Proxy only cannot be applied reliably.** It ran 78% disagreement against 0% for Directly measurable and 9% for Verification contested, and all three auditors independently reported it was repeatedly the nearest alternative and almost never won. Every Proxy only assignment has therefore been downgraded to `guess`, including the ones the auditor did not sample.');
w();
w('This matters for reading everything above: the tiers that carry the argument are the two that held up. Tier 1 and tier 3 are reliable; the residual category between them is not, and a future version should either define it more sharply or drop it.');
w();
w('### Taxonomy gaps found by audit');
w();
w('Three cases where the seven-type taxonomy has no right answer, all surfaced independently by blind auditors:');
w();
w('- **Closed-loop control of a physical system** has no home. Fusion plasma control chooses no experiments, so it is not autonomous experimentation, and it builds nothing, so it is not physical build. This is a defensible eighth category.');
w('- **Gaps where AI is the object rather than the instrument** (AI misuse, rogue AI, narrow reasoning) have no safety-and-robustness-research bucket.');
w('- **Composite gaps** bundle sub-problems that would take different types *and different tiers*, so a single primary loses real information.');
w();
w('## Confidence flags');
w();
w('| Dimension | Confident | Guess |');
w('|---|---:|---:|');
for (const [d, t, where] of [['Outcome', 'gap_outcomes', ''], ['Primary AI type', 'gap_ai_types', 'WHERE is_primary=1'], ['Measurability tier', 'gap_measurability', '']]) {
  const c = one(`SELECT count(*) c FROM ${t} ${where} ${where ? 'AND' : 'WHERE'} confidence='confident'`).c;
  const g = one(`SELECT count(*) c FROM ${t} ${where} ${where ? 'AND' : 'WHERE'} confidence='guess'`).c;
  w(`| ${d} | ${c} | ${g} |`);
}
w();

writeFileSync(`${root}docs/findings.md`, L.join('\n'));
console.log(`wrote docs/findings.md (${L.length} lines)`);
