#!/usr/bin/env node
// Profile the imported baseline and write docs/integrity-report.md.
//
// The brief lists five "known holes, worth confirming during the work". This
// confirms or refutes each against the actual export rather than taking them on
// trust, and surfaces anything else the data shows. Findings here feed the cover
// note: telling Convergent something true about their own export is the cheapest
// credibility available.

import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('..', import.meta.url).pathname;
const db = new DatabaseSync(`${root}db/gapmap.sqlite`);
const all = (sql, ...p) => db.prepare(sql).all(...p);
const one = (sql, ...p) => db.prepare(sql).get(...p);

const snapshot = '2026-07-29';
const source = JSON.parse(readFileSync(`${root}data/baseline/${snapshot}/gapmap-data.json`, 'utf8'));

const L = [];
const w = (s = '') => L.push(s);

w(`# Baseline integrity report — Convergent Research Gap Map export ${snapshot}`);
w();
w(`Generated by \`engine/integrity-report.mjs\`. Source: \`data/baseline/${snapshot}/\`, export date ${source.metadata.exportDate}, version ${source.metadata.version}.`);
w();
w('## Declared vs. actual counts');
w();
w('| Entity | Declared | Actual | |');
w('|---|---:|---:|---|');
for (const [k, table] of [['fields', 'gm_fields'], ['gaps', 'gm_gaps'], ['capabilities', 'gm_capabilities'], ['resources', 'gm_resources']]) {
  const actual = one(`SELECT count(*) c FROM ${table}`).c;
  const declared = source.metadata.counts[k];
  w(`| ${k} | ${declared} | ${actual} | ${declared === actual ? 'ok' : '**MISMATCH**'} |`);
}
w();

w("## The brief's five known holes, checked");
w();
const hasRank = source.gaps.some((g) => 'rank' in g) || source.capabilities.some((c) => 'rank' in c);
w(`**1. No \`rank\` field, though the site sorts by rank.** ${hasRank ? 'Refuted — a rank field is present.' : 'Confirmed.'} No gap or capability record carries a rank, ordering or priority key. Whatever backs the site\'s rank sort is not in the export, so rank cannot be reconstructed and is not something this augmentation touches.`);
w();

const gapTags = {}, capTags = {};
for (const g of source.gaps) for (const t of g.tags ?? []) gapTags[t] = (gapTags[t] || 0) + 1;
for (const c of source.capabilities) for (const t of c.tags ?? []) capTags[t] = (capTags[t] || 0) + 1;
const fmt = (o) => Object.entries(o).sort((a, b) => b[1] - a[1]).map(([k, v]) => `\`${k}\` (${v})`).join(', ') || 'none';
w(`**2. \`tags\` has no documented enum.** Confirmed — no enum is declared in \`schema.json\`. Observed values:`);
w();
w(`- On gaps: ${fmt(gapTags)}`);
w(`- On capabilities: ${fmt(capTags)}`);
w();
w(`Only ${Object.values(gapTags).reduce((a, b) => a + b, 0)} tag assignments exist across all ${source.gaps.length} gaps, so gap tags carry almost no signal. The risk vocabulary the brief expects — safety, security, governance/ethics — does appear, but almost entirely on capabilities.`);
w();

const declaredTypes = source.resourceTypes ?? null;
const obsTypes = {};
for (const r of source.resources) for (const t of r.types ?? []) obsTypes[t] = (obsTypes[t] || 0) + 1;
w(`**3. Resource \`types\` has no documented enum.** Partly refuted. \`schema.json\` declares none, but \`gapmap-data.json\` carries an undocumented top-level \`resourceTypes\` array — ${declaredTypes ? declaredTypes.length : 0} values — that neither the README nor the schema mentions. Observed usage:`);
w();
w('| Type | Count |');
w('|---|---:|');
for (const [k, v] of Object.entries(obsTypes).sort((a, b) => b[1] - a[1])) w(`| ${k} | ${v} |`);
w();
const unused = (declaredTypes ?? []).filter((t) => !(t in obsTypes));
const undeclared = Object.keys(obsTypes).filter((t) => !(declaredTypes ?? []).includes(t));
w(`Declared but unused: ${unused.length ? unused.map((t) => `\`${t}\``).join(', ') : 'none'}. Used but undeclared: ${undeclared.length ? undeclared.map((t) => `\`${t}\``).join(', ') : 'none'}.`);
w();

const hasTs = source.gaps.some((g) => 'updatedAt' in g || 'createdAt' in g || 'lastModified' in g);
w(`**4. No per-record timestamps or version numbers.** ${hasTs ? 'Refuted.' : 'Confirmed.'} The only temporal marker is the export-level \`exportDate\`. Change over time cannot be measured from this export alone, which is why \`data/baseline/${snapshot}/\` is committed verbatim and hash-pinned: it is the only way a future export can be diffed against this state.`);
w();
w('**5. Nothing marks a capability as necessary, sufficient, or partial for its linked gap.** Confirmed. Edges are untyped — a capability that would fully close a gap and one that nibbles at it are indistinguishable in the data. This is the single most consequential absence for anyone trying to reason about what actually unblocks what, and it is why the critical-path work in Phase 5 has to reconstruct link semantics by hand.');
w();

w('## Additional findings not in the brief');
w();
const capsWithGaps = source.capabilities.filter((c) => (c.gaps ?? []).length).length;
const edgeCount = one('SELECT count(*) c FROM gm_gap_capabilities').c;
w(`### The bipartite graph is only half-populated`);
w();
w(`\`schema.json\` documents \`capabilities[].gaps\` as "IDs of R&D gaps addressed by this capability". In this export **that array is empty for all ${source.capabilities.length} capabilities** (${capsWithGaps} populated). All ${edgeCount} edges exist solely on the gap side, in \`gaps[].foundationalCapabilities\`.`);
w();
w('Consequences for a consumer: the graph is still complete, because the gap side carries every edge, but any code that trusts the documented capability-side field builds an empty graph and silently reports that no capability addresses any gap. Anyone starting from `capabilities.json` alone gets nothing. This is a straightforward export bug and probably the most useful single thing to tell them.');
w();

const noDesc = source.capabilities.filter((c) => !c.description);
w(`### Two capabilities have no description`);
w();
for (const c of noDesc) w(`- \`${c.id}\` — ${c.name}`);
w();
w('`description` is listed as required in their own `schema.json`, so these two records fail their own schema.');
w();

const usedR = new Set();
for (const c of source.capabilities) for (const r of c.resources ?? []) usedR.add(r);
const orphanR = source.resources.filter((r) => !usedR.has(r.id));
const capsNoRes = source.capabilities.filter((c) => !(c.resources ?? []).length);
w(`### Orphans`);
w();
w(`- ${orphanR.length} resources are referenced by no capability, so they are unreachable by navigation.`);
w(`- ${capsNoRes.length} capabilities carry no resources at all.`);
w(`- Every gap has at least one capability, and every gap has a field. No dangling references in any direction.`);
w();

w('## Shape of the labeling job');
w();
const perField = all(`
  SELECT f.name AS field, count(*) AS n
  FROM gm_gaps g JOIN gm_fields f ON f.id = g.field_id
  GROUP BY f.name ORDER BY n DESC, f.name`);
w('| Field | Gaps |');
w('|---|---:|');
for (const r of perField) w(`| ${r.field} | ${r.n} |`);
w();
const lens = source.gaps.map((g) => g.description.split(/\s+/).length).sort((a, b) => a - b);
const q = (p) => lens[Math.floor(lens.length * p)];
w(`Gap descriptions run ${lens[0]}–${lens[lens.length - 1]} words, median ${q(0.5)}, interquartile ${q(0.25)}–${q(0.75)}. That is the house format any new gap has to match; see \`methodology/house-format.md\`.`);
w();
w(`Astrophysics has ${perField.find((r) => r.field === 'Astrophysics')?.n} gaps and Metascience ${perField.find((r) => r.field === 'Metascience')?.n}, matching the brief. Thin coverage in exactly the fields of interest is the expected pattern under the thesis, not an artifact of the export.`);
w();

writeFileSync(`${root}docs/integrity-report.md`, L.join('\n'));
console.log(`wrote docs/integrity-report.md (${L.length} lines)`);
